### ISSUE TITLE
Readme and Hosted Site

### ISSUE THREAD

**Issue by BartBucknill** [fac-12/ssbt-ToDo#32]
I'm notoriously bad at writing readmes so feel very hypocritical saying this, nonetheless it would be great to have a readme to explain the project, what you've learnt etc.
Would be even better to have a link to the site at the top of the repo main page (their is a field for it).
Github pages is the easiest place to host it if you haven't yet done so; you can turn it on in the repo settings.

**Comment by shannonjensen** [comment]
Resolved
