### ISSUE TITLE
Addtodo submit button temperemental

### ISSUE THREAD

**Issue by parkhabit** [fac-12/ssbt-ToDo#36]
Sometimes when we click or enter on the submit button the todo text doesn't get added to the screen. We took a screen shot of the console when this happened.
![screen shot 2017-11-03 at 10 08 35](https://user-images.githubusercontent.com/16639540/32368867-18a78c58-c07f-11e7-9aeb-946f5de9acf9.png)

**Comment by BartBucknill** [comment]
I'm also unable to add todos. I see an 'unexpected end of input' error in console originating in dom.js. This suggests a syntax error.

**Comment by absorpheus** [comment]
I am getting the same issue. It seems to happen after you try to add something that is empty.

When you add something that is empty, you get an popup error message and then when you try to add a todo with some text, an error comes into the console

**Comment by BartBucknill** [comment]
After the latest update I now see in console 'Uncaught SyntaxError: missing ) after argument list' originating in dom.js.
Regarding @AbdullahChaudhry comment, this is different from what I'm seeing. Currently due to the syntax error I'm unable to add any todos empty or not.

**Comment by BartBucknill** [comment]
now working!
I had another error related to local storage, I had to turn off 'Block third-party cookies' in chrome in order to get local storage working.

**Comment by shannonjensen** [comment]
Sorry for the syntax errors that messed things up this morning. It's bc we quickly did conflict resolution in github instead of in the code editor. And then did the same thing again... Lesson learned!

**Comment by shannonjensen** [comment]
Interesting re local storage being messed up by blocking cookies @BartBucknill. My understanding were that they were different. Will look into...

**Comment by BartBucknill** [comment]
@shannonjensen They are different - although chrome calls the functionality blocking cookies, I think it in fact does more than this. A little googling seemed to reveal quite a few issues raised. Also this only seemed to affect running on local host, not when on the github pages site.
