### ISSUE TITLE
Great work on writing tests

### ISSUE THREAD

**Issue by absorpheus** [fac-12/ssbt-ToDo#44]
I just ran your tests (by initialising npm and then installing the dependencies manually) and they are all passing! Great work : )

![screen shot 2017-11-03 at 10 17 42](https://user-images.githubusercontent.com/19255312/32369229-5ae56a94-c080-11e7-9031-5bd680e4c2eb.png)

**Comment by shannonjensen** [comment]
Sorry for the dependencies not being set up correctly. Ran npm init and installed tape but forgot the dev flags initially so deleted the folders and reinstalled with dev flags but that bootleg approach didnt work i suppose...
