### ISSUE TITLE
Git - Link your commits to issue numbers

### ISSUE THREAD

**Issue by absorpheus** [fac-12/ssbt-ToDo#50]
When writing a commit message it's useful to include the issue number, so when you push up your branch it can be referenced by GitHub.

When doing a git commit, For example: 

git commit -m "Add todo submit button #36"

OR 

git commit -m "Add todo submit button

Relates #36"

In the second example above you just hit enter after button and continue writing the message on a new line, remember to close it by including a closing " 

You can also reference issue numbers when making a Pull Request on GitHub, which will then be turned into links to that issue. For example, if I make a new PR I could include the issue number in the PR like this:

Relates to #36 

This way you can click on number 36 and it will take you directly to the issue the PR is related to.

**Comment by shannonjensen** [comment]
Yes we've been quite verbal about everything rather than raising issues since we're all sitting together. Need to improve on using the issues....
