### ISSUE TITLE
Accessibility - buttons

### ISSUE THREAD

**Issue by parkhabit** [fac-12/ssbt-ToDo#53]
![screen shot 2017-11-03 at 10 55 45](https://user-images.githubusercontent.com/16639540/32370610-aab8e744-c085-11e7-9df8-beca1255a1fa.png)
It seems like your buttons don't have a name attribute and it's bringing down your accessibility score.

**Comment by rb50** [comment]
Thanks for the feedback! I've now added aria labels to all the buttons :)
